# Generated by Django 5.2.7 on 2025-10-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantingsite',
            options={'permissions': (('manage_sites', 'Can manage planting sites'),)},
        ),
    ]
