# Generated by Django 5.2.7 on 2025-10-21 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('co2_estimate_kg_per_year', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.CharField(max_length=64, unique=True)),
                ('planting_date', models.DateField()),
                ('number_of_seedlings', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('dead', 'Dead'), ('replanted', 'Replanted')], default='alive', max_length=16)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiary')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.treespecies')),
            ],
        ),
        migrations.CreateModel(
            name='TreeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('dead', 'Dead'), ('replanted', 'Replanted')], max_length=16)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='trees.tree')),
            ],
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['planting_date'], name='trees_tree_plantin_0ebfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['latitude', 'longitude'], name='trees_tree_latitud_b623f8_idx'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['status'], name='trees_tree_status_4f3b05_idx'),
        ),
    ]
