# Generated by Django 5.2.7 on 2025-10-23 04:31

import trees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_auto_add_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treeupdate',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='tree',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=trees.models.tree_qr_upload_to),
        ),
    ]
