# Generated by Django 5.2.7 on 2025-10-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('field_officer', 'Field Officer'), ('project_manager', 'Project Manager'), ('volunteer', 'Volunteer'), ('beneficiary', 'Beneficiary Liaison')], default='volunteer', max_length=32),
        ),
    ]
