# Generated by Django 5.2.7 on 2025-10-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('field_officer', 'Field Officer'), ('field', 'Field Officer'), ('partner', 'Partner Institution'), ('partner_institution', 'Partner Institution'), ('project_manager', 'Project Manager'), ('volunteer', 'Volunteer'), ('beneficiary', 'Beneficiary Liaison'), ('guest', 'Guest User'), ('community', 'Community Representative')], default='volunteer', max_length=32),
        ),
    ]
