# Generated by Django 5.2.7 on 2025-10-28 10:00

import reports.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=reports.models.reports_upload_to),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='report_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('partner', 'Partner'), ('public', 'Public')], default='summary', max_length=32),
        ),
    ]
