# Generated by Django - initial migration for qrcodes

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=128, blank=True)),
                ('image', models.ImageField(upload_to='qrcodes/%s', blank=True, null=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tree', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='trees.Tree')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='beneficiaries.Plantingsite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
