# Generated by Django 5.2.7 on 2025-10-22 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('media_app', '0001_initial'),
        ('monitoring', '0001_initial'),
        ('trees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_planted', models.PositiveIntegerField(default=0)),
                ('surviving', models.PositiveIntegerField(default=0)),
                ('growth_notes', models.TextField(blank=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('failed', 'Failed')], default='healthy', max_length=16)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('weather', models.JSONField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ManyToManyField(blank=True, to='media_app.media')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.plantingsite')),
                ('tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.tree')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
