import sqlite3
conn=sqlite3.connect('db.sqlite3')
cur=conn.cursor()
cur.execute("SELECT app, name, applied FROM django_migrations WHERE app='monitoring'")
print('before:', cur.fetchall())
cur.execute("DELETE FROM django_migrations WHERE app='monitoring' AND name='0002_monitoringreport'")
conn.commit()
cur.execute("SELECT app, name, applied FROM django_migrations WHERE app='monitoring'")
print('after:', cur.fetchall())
conn.close()
print('done')