name: setup-allauth

on:
  workflow_dispatch:

jobs:
  setup-socialapp:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: tawi_project.settings
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python manage.py migrate --noinput

      - name: Setup Google SocialApp
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          SITE_ID: ${{ secrets.SITE_ID }}
        run: |
          python scripts/setup_allauth.py

      - name: Verify SocialApp
        run: |
          python manage.py shell -c "from allauth.socialaccount.models import SocialApp; print(list(SocialApp.objects.filter(provider='google').values('client_id','name')))"
